### ISSUE TITLE
Alteração de senha não está criptografando

### ISSUE THREAD

**Issue by rickgrana** [rickgrana/sais2#11]
Caminho: frontend > Alteração de senha

Acredito que a alteração de senha está fazendo a senha ficar descriptografado no banco.

**Comment by alinemaar** [comment]
Ao realizar alguns testes ao alterar senha via mobile e desktop, foi verificado que a senha está criptografada no banco ;

**Comment by alinemaar** [comment]
Ao realizar mais um teste, foi encontrado o erro no cadastro de parceria. Corrigido
