### ISSUE TITLE
Oferta: Destaques

### ISSUE THREAD

**Issue by rickgrana** [rickgrana/sais2#21]
Acrescentar aos Destaques uma opção que informe se a Oferta está em Destaque ou não.

**Comment by raicleysantana** [comment]
Feito

**Comment by rickgrana** [comment]
Não colocar o Destaque no formulário, mas como uma opção no Visualizar

**Comment by alinemaar** [comment]
Em Andamento

**Comment by alinemaar** [comment]
Concluído.
