### ISSUE TITLE
Turmas: Matriculas

### ISSUE THREAD

**Issue by rickgrana** [rickgrana/sais2#22]
Backend > Turmas

Acrescentar campos:

Matricula: CHAR(1) com as opções (I)mediatas, (A) partir de
Prazo Matriculas: VARCHAR(255)

No formulario, se matriculas forem imediatas, nao exibir o prazo. Se for 'A partir de', exigir o prazo.

**Comment by raicleysantana** [comment]
Fazendo

**Comment by raicleysantana** [comment]
concluido

**Comment by rickgrana** [comment]
Preencher as turmas antigas com valor 'I'

**Comment by raicleysantana** [comment]
Feito
