### ISSUE TITLE
Oferta: Segunda Mensalidade

### ISSUE THREAD

**Issue by rickgrana** [rickgrana/sais2#23]
Backend > Oferta

Acrescentar campo 'SEGUNDA MENSALIDADE', varchar(255)

No formulário, aparecer: 'Segunda Mensalidade em'

* O campo indica a partir de quando será o pagamento da segunda mensalidade

**Comment by alinemaar** [comment]
Em Andamento

**Comment by alinemaar** [comment]
Concluído

**Comment by rickgrana** [comment]
Placeholder: informe uma Data ou Período

**Comment by rickgrana** [comment]
Diminuir um pouco o campo

**Comment by rickgrana** [comment]
A disposição ficou quebrada

![image](https://user-images.githubusercontent.com/15691356/79909845-a78fe500-83eb-11ea-984f-918aae02d453.png)

**Comment by alinemaar** [comment]
Concluído
