### ISSUE TITLE
Inscrição confirmada: adicionar opção de Confirmar Matricula

### ISSUE THREAD

**Issue by rickgrana** [rickgrana/sais2#24]
Backend > Inscricao > VIsualizar

Para inscrições confirmadas, acrescentar a opção para confirmar matricula, presente na pagina inicial

**Comment by raicleysantana** [comment]
Concluido

**Comment by rickgrana** [comment]
Não encontrei a opção

**Comment by alinemaar** [comment]
o Confirmar não é o mesmo que Confirmar Matricula ?
