### ISSUE TITLE
Inscrição: Impressão de Espelho

### ISSUE THREAD

**Issue by rickgrana** [rickgrana/sais2#25]
Backend > Inscricao > Espelho

Fazer impressão de Espelho da Inscrição com todos os dados

**Comment by alinemaar** [comment]
Em Andamento.

**Comment by alinemaar** [comment]
Concluído .

**Comment by rickgrana** [comment]
Não exibir valor de desconto e valor de matricula se for zero

**Comment by rickgrana** [comment]
Traduzir informação do Boleto Emitido

**Comment by rickgrana** [comment]
Trocar label 'Usuário' por 'Nome'

**Comment by rickgrana** [comment]
Aumentar espaço para email e CPF

**Comment by rickgrana** [comment]
No cabeçalho, à direita, colocar em letras grandes:

INSCRIÇÃO #XXXX
Situação: (situação)

**Comment by rickgrana** [comment]
Trocar 'Informações do Usuário' por 'Dados Pessoais'

**Comment by rickgrana** [comment]
Remover a situação dos Dados Pessoais

**Comment by rickgrana** [comment]
Colocar a hora na data de inscricao

**Comment by rickgrana** [comment]
Falta o simbolo R$ antes da taxa de adesão

**Comment by rickgrana** [comment]
Substituir 'Outras Informações' por 'Pagamento'

**Comment by alinemaar** [comment]
Em Andamento

**Comment by alinemaar** [comment]
Alterações Concluídas;

**Comment by rickgrana** [comment]
> Traduzir informação do Boleto Emitido

Faltou este

**Comment by rickgrana** [comment]
Colocar a Bolsa e Valor com Desconto na mesma linha

**Comment by rickgrana** [comment]
Formatar o campo de telefone

**Comment by alinemaar** [comment]
Concluído.
