### ISSUE TITLE
Exibir cursos inativos

### ISSUE THREAD

**Issue by rickgrana** [rickgrana/sais2#26]
No fronntend, exibir cursos que nao estejam ativos.

Os cursos inativos serão exibidos por ultimo na listagem, com coloração acinzentada e, ao invés dos valores, mostrar texto 'OFERTA NÃO DISPONIVEL'.

O usuário não poderá se inscrever neste curso.

**Comment by raicleysantana** [comment]
EM andamento

**Comment by raicleysantana** [comment]
Concluido

**Comment by rickgrana** [comment]
Mudar o restante do quadro para cor acizentada, parece que está ativo ainda

**Comment by alinemaar** [comment]
Ajustes realizados , concluído.
