### ISSUE TITLE
Registrar por  Facebook

### ISSUE THREAD

**Issue by rickgrana** [rickgrana/sais2#30]
Permitir registrar conta pelo Facebook

Registrar os dados possíveis. Se nao houver um campo, permitir registrar assim mesmo e fazer a devida anotação.

Criar um campo no User que indique por onde se registrou: (origem: Facebook)

**Comment by rickgrana** [comment]
Se houver necessidade de efetuar ajuste pelo face, testar com uma pagina própria sua e fazer as devidas anotações dos passos

**Comment by raicleysantana** [comment]
Em andamento

**Comment by raicleysantana** [comment]
Passos https://www.notion.so/Get-Started-Sigin-Facebook-8cf2a3dcff254134adaba45c668d946a

**Comment by raicleysantana** [comment]
concluido

**Comment by rickgrana** [comment]
Testado e OK.
