### ISSUE TITLE
Registrar pelo Gmail

### ISSUE THREAD

**Issue by rickgrana** [rickgrana/sais2#31]
Permitir registrar conta pelo Gmail

Registrar os dados possíveis. Se nao houver um campo, permitir registrar assim mesmo e fazer a devida anotação.

Em User, indicar por onde se registrou (origem: gmail)

**Comment by raicleysantana** [comment]
passos https://www.notion.so/Get-Started-Signin-Google-503cc07a83564b82b5c712cc6008e351#91a42893c1ee4bf0a286db2033a5dcbf
