### ISSUE TITLE
Criar Banco de Imagens

### ISSUE THREAD

**Issue by rickgrana** [rickgrana/sais2#33]
backend > cadastros > Imagens

Permissão: apenas Adminstrator

Tabela: imagem
campos:
   id, PK, AI
  dtcriacao, datetime not null,
  tags: string(500) not null

**Comment by rickgrana** [comment]
No formulário, deverá ter:
upload de imagem, se possível utilizar o widget https://www.yiiframework.com/extension/yii2-easy-uploader

tags: Permitir cadastrar varias tags com Select2, ex: TI, Informática, Computação

**Comment by rickgrana** [comment]
Na listagem mostrar imagens pelas mais recentes.

Exibir campo de texto para pesquisa por tag.

Na listagem, mostrar imagem em 50% da largura, com as tags ao lado.

**Comment by alinemaar** [comment]
Inciado

**Comment by alinemaar** [comment]
Concluído;

**Comment by rickgrana** [comment]
Layout está um pouco bagunçado

![image](https://user-images.githubusercontent.com/15691356/79904903-6dbae080-83e3-11ea-836b-5bb37337e173.png)

**Comment by rickgrana** [comment]
Melhorar layout.

Falta traduzir

![image](https://user-images.githubusercontent.com/15691356/79905010-9642da80-83e3-11ea-88cd-51b264630ca3.png)

**Comment by rickgrana** [comment]
Nao parece estar utilizándoos widget solicitado

**Comment by alinemaar** [comment]
Em Andamento

**Comment by alinemaar** [comment]
Atividade em andamento, procurando uma nova solução para a actionCreate que agora não está funcionado após o novo plugin

**Comment by alinemaar** [comment]
Concluído
