### ISSUE TITLE
Ajustes na visualização da Inscrição

### ISSUE THREAD

**Issue by rickgrana** [rickgrana/sais2#35]
Traduzir informação do Boleto Emitido

Resumir Labels de data: "Processamento", "Vencimento" e exibir hora quando tiver

Link para visualizar o boleto.

**Comment by alinemaar** [comment]
Em Andamento

**Comment by alinemaar** [comment]
Concluído.

**Comment by rickgrana** [comment]
Adicionar API para mandar whastapp a partir do contato

**Comment by rickgrana** [comment]
Exibir valor com desconto apenas quando tiver valor

**Comment by rickgrana** [comment]
Idem para Valor da Matricula

**Comment by rickgrana** [comment]
Valor com desconto deve vir após o %

**Comment by rickgrana** [comment]
Traduzir Boleto EMitido

**Comment by rickgrana** [comment]
Trazer link para acessar o boleto

**Comment by rickgrana** [comment]
Corrigir: Dados DA Oferta

**Comment by rickgrana** [comment]
Colocar o conteúdo do quadro 'Inscrições', fora de panel.
Retirar o RG desta área e adicionar 'Inscrito em ' + data e hora inscricao
 

'Comprovante' e 'Espelho' viram botões de ação no canto direito

Retirar o ":"dos labels

**Comment by alinemaar** [comment]
Em Andamento

**Comment by alinemaar** [comment]
Em Andamento

**Comment by alinemaar** [comment]
> Trazer link para acessar o boleto

este link já existe no menu lateral

**Comment by alinemaar** [comment]
Concluído.
