### ISSUE TITLE
IES: usuários

### ISSUE THREAD

**Issue by rickgrana** [rickgrana/sais2#37]
Backend > Instituições

Na visualização, voltar a aba que listava e permitia inserir usuários às Instituições.

A opção existia no visualizar e nao se encontra mais la

**Comment by alinemaar** [comment]
Em Andamento

**Comment by alinemaar** [comment]
Concluído.

**Comment by rickgrana** [comment]
Se ocorre um erro de validação, está exibindo o código do usuário no Select2.

Melhorar a msg de erro quando duplicado tb

**Comment by rickgrana** [comment]
Colocar a aba antes de 'Outras Informacoes'

**Comment by alinemaar** [comment]
Em Andamento

**Comment by alinemaar** [comment]
Concluído.
