### ISSUE TITLE
Melhorias no Certificado de Bolsista

### ISSUE THREAD

**Issue by rickgrana** [rickgrana/sais2#39]
Backend > Inscricao > Certificado

Colocar em modo paisagem.

Adicionar uma imagem de fundo, que deve ser configurada em Configurações > Imagens. (Se basear no certificado do SGCE)

Título: CERTIFICADO

Texto (com recuo na primeira linha): Certificamos para os devidos fins que [NOME DO BOLSISTA], CPF: XXXX, é bolsista do BOLSAPRAVOCE, no curso de [NOME DO SERVICO], turma [NOME DA TURMA, se houve], turno [TURNO], modalidade [modalidade], na instituição [IES], com bolsa de estudos válida no percentual de X%, desconto este válido apenas a partir da efetivação da matrícula junto à instituição de ensino e nos demais termos válidos no BOLSAPRAVOCE.

Manaus/AM, data atual (alinhado à direita)

BOLSAPRAVOCE (centralizado e negrito)

**Comment by rickgrana** [comment]
o QRCODE vem alinhado à esquerda no canto inferior esquerdo, como no SGCE

**Comment by alinemaar** [comment]
Em Andamento

**Comment by alinemaar** [comment]
Atividade Iniciada.

**Comment by alinemaar** [comment]
Concluído.
