### ISSUE TITLE
Lembrete de Oferta

### ISSUE THREAD

**Issue by rickgrana** [rickgrana/sais2#41]
Quando a vaga não estiver disponível, exibir botão 'Tenho interesse nesta vaga'.

Abrirá um Alert ou Modal para o Usuário com o texto:

Desculpe, esta oferta não está disponível no momento.

Gostaria que te avisássemos quando houver vaga neste curso?

e botão SIM.

Se confirmar, enviar AJAX que salvará em uma tabela USER_LEMBRETE, prefixo userlem. com os campos:

- código do usuário, FK
- código do serviço, FK

O código do usuário + código do serviço deve ser UNICO. Se já existe registrado, apenas ignorar.

Quando retornar, exibir o aviso 'Lembrete criado. Avisaremos quando houver disponibilidade do curso'

Não recarregar a página.

**Comment by raicleysantana** [comment]
Em andamento

**Comment by raicleysantana** [comment]
Concluído
