### ISSUE TITLE
Trocar paginação dos cursos por Infinite Scroll

### ISSUE THREAD

**Issue by rickgrana** [rickgrana/sais2#42]
Ao invés do pager da lista de cursos da pagina inicial, exibir um botão 'Carregar mais ofertas', que deve ser um btn-block abaixo da lista.

Ao clicar, carregar a nova página de cursos através de ajax.

**Comment by alinemaar** [comment]
Em Andamento

**Comment by alinemaar** [comment]
Em Andamento

**Comment by alinemaar** [comment]
Concluído.
