### ISSUE TITLE
Permitir colocar 3 Taxas de Adesão

### ISSUE THREAD

**Issue by rickgrana** [rickgrana/sais2#6]
A primeira taxa vai ser até o dia 10

A segunda taxa vai ser até o dia 20

A terceira taxa a partir do dia 21 do mês.

**Comment by rickgrana** [comment]
Estas taxas deverão aparecer no frontend

**Comment by alinemaar** [comment]
Em Andamento

**Comment by alinemaar** [comment]
Concluído;
