### ISSUE TITLE
Relatório: Métricas por Data

### ISSUE THREAD

**Issue by rickgrana** [rickgrana/sais2#8]
Criar relatório que mostre a quantidade de IPs distintos por Data

Que possua a opção 'Nos últimos 7 dias' e 'Nos últimos 14 dias'.

**Comment by raicleysantana** [comment]
Fazendo

**Comment by raicleysantana** [comment]
Concluido

**Comment by rickgrana** [comment]
Erro: 
![image](https://user-images.githubusercontent.com/15691356/79910272-68ae5f00-83ec-11ea-9118-fcccb90e7614.png)

**Comment by raicleysantana** [comment]
Corrigido
