### ISSUE TITLE
Relatório: Relação de Métricas

### ISSUE THREAD

**Issue by rickgrana** [rickgrana/sais2#9]
Mostrar todas as Métricas em um dia específico.

Que venha como padrão a Data Atual tenha opção de 'Data Anterior'  e 'Data Posterior' para navegar.

**Comment by raicleysantana** [comment]
em andamento

**Comment by raicleysantana** [comment]
Concluido

**Comment by rickgrana** [comment]
Não está abrindo na data atual

**Comment by rickgrana** [comment]
Nao está exibindo a hora

**Comment by raicleysantana** [comment]
Corrigido

**Comment by rickgrana** [comment]
faltam os segundos

**Comment by alinemaar** [comment]
Concluído.
